force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ExternalPostsLoaderTest.cls
@isTest
public with sharing class ExternalPostsLoaderTest {
    @isTest
    public static void getPostsTest() { 
        Test.setMock(HttpCalloutMock.class, new PostsHttpCalloutMock());
        
        Test.startTest();        
        System.enqueueJob(new ExternalPostsLoader());
        Test.stopTest();

        Post__c post = [SELECT Id, ExternalId__c FROM Post__c ORDER BY ExternalId__c LIMIT 1];
        Integer expected = 1;
        Integer actual = Integer.valueOf(post.ExternalId__c);

        System.assertEquals(expected, actual, 'External id must be equal to external id of first post');
    }   
}