force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Post__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExternalPostsLoader.cls
public with sharing class ExternalPostsLoader implements Queueable, Database.AllowsCallouts {
    private class PostDTO {
        public Integer Id;
        public Integer UserId;
        public String Title;
        public string Body;
    }

    public void execute(QueueableContext context) {
        List<Post__c> postsToUpsert = new List<Post__c>();
        List<PostDTO> posts = new List<PostDTO>();

        Http http = new Http();

        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://jsonplaceholder.typicode.com/posts');
        request.setMethod('GET');
        
        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            posts = (List<PostDTO>) JSON.deserialize(response.getBody(), List<PostDTO>.class);
            for (PostDTO post : posts) { 
                Post__c postToupsert = new Post__c(ExternalId__c = post.Id, 
                                                    UserId__c = post.UserId,
                                                    Title__c = post.Title,
                                                    Body__c = post.Body);                
                postsToUpsert.add(postToupsert);
            }
        }

        if (!postsToUpsert.isEmpty()) {
            upsert postsToUpsert ExternalId__c;
        }

        System.enqueueJob(new ExternalCommentsLoader()); 
    }
}