force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PostComment__c/PostComment__c.object-meta.xml
<CustomObject>
    <label>Post Comment</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Post Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PostComment__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostComment__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Post Comments</relationshipLabel>
    <relationshipName>PostComments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PostController.cls
public with sharing class PostController {
    
    @AuraEnabled
    public static Response getPostComments(String postId){
        Response resp;
        try {
            List<PostComment__c> comments = [SELECT Id, Name__c, ExternalId__c, Email__c, Body__c
                                            FROM PostComment__c
                                            WHERE Post__c =: postId];
            resp = new Response(comments);  
        } catch (Exception e) {
            resp = new Response(e);
        }

        return resp;
    }
}