force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PostComment__c/PostComment__c.object-meta.xml
<CustomObject>
    <label>Post Comment</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Post Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PostComment__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostComment__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Post Comments</relationshipLabel>
    <relationshipName>PostComments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExternalCommentsLoader.cls
public with sharing class ExternalCommentsLoader implements Queueable, Database.AllowsCallouts {
    private class CommentDTO {
        public Integer Id;
        public Integer PostId;
        public String Name;
        public String Email;
        public string Body;
    }

    public void execute(QueueableContext context) {
        List<PostComment__c> postCommentsToUpsert = new List<PostComment__c>();
        List<CommentDTO> comments = new List<CommentDTO>();

        Http http = new Http();

        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://jsonplaceholder.typicode.com/comments');
        request.setMethod('GET');
        
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            comments = (List<CommentDTO>) JSON.deserialize(response.getBody(), List<CommentDTO>.class);
            
            for (CommentDTO comment : comments) { 
                Post__c post = new Post__c(ExternalId__c = comment.PostId);
                PostComment__c commentToupsert = new PostComment__c(ExternalId__c = comment.Id,
                                                                    Post__r = post,
                                                                    Name__c = comment.Name,
                                                                    Email__c = comment.Email,
                                                                    Body__c = comment.Body);                
                                                            
                postCommentsToUpsert.add(commentToupsert);
            }
        }

        if (!postCommentsToUpsert.isEmpty()) {
            upsert postCommentsToUpsert ExternalId__c;
        }

        System.enqueueJob(new ExternalPostUpdater());
    }
}