force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Post__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PostSaveController.cls
public with sharing class PostSaveController {
  
    @AuraEnabled
    public static Response createPost(String externalId, String userId, String title, String body) {
        Post__c post = new Post__c();
        post.ExternalId__c = Integer.valueOf(externalId);
        post.UserId__c = Integer.valueOf(userId);
        post.Title__c = title;
        post.Body__c = body;

        Response resp;
        try {
            insert post;
        } catch (Exception e) {
            resp = new Response(e);
        }
        return resp;
    }
}