force-app/main/default/objects/EmployeeTest__c/EmployeeTest__c.object-meta.xml
<CustomObject>
    <label>Employee Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmployeeTest__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TestQuestion__c/TestQuestion__c.object-meta.xml
<CustomObject>
    <label>Test Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestion__c/fields/Employee_Test__c.field-meta.xml
<CustomField>
    <fullName>Employee_Test__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Test</label>
    <referenceTo>EmployeeTest__c</referenceTo>
    <relationshipName>TestQuestions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestQuestion__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <summaryForeignKey>TestQuestionAnswer__c.TestQuestion__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TestQuestionAnswer__c/TestQuestionAnswer__c.object-meta.xml
<CustomObject>
    <label>Test Question Answer</label>
    <nameField>
        <label>Test Question Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestionAnswer__c/fields/TestQuestion__c.field-meta.xml
<CustomField>
    <fullName>TestQuestion__c</fullName>
    <label>Test Question</label>
    <referenceTo>TestQuestion__c</referenceTo>
    <relationshipLabel>Test Question Answers</relationshipLabel>
    <relationshipName>TestQuestionAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestQuestionAnswerTriggerHandler.cls
public with sharing class TestQuestionAnswerTriggerHandler {
    public static void changeEmployeeTestNumberAnswers(List<TestQuestionAnswer__c> questionAnswers) {
        List<EmployeeTest__c> testsToUpdate = new List<EmployeeTest__c>();

        Set<Id> testsIds = getTestIdsForQuestionAnswers(questionAnswers);        
        List<AggregateResult> result = [SELECT TestQuestion__r.Employee_test__c TestId, 
                                            MIN(TestQuestion__r.Employee_test__r.NumberAnswers__c) OldNumberAnswers, 
                                            COUNT(Id) NumberAnswers
                                        FROM TestQuestionAnswer__c
                                        WHERE TestQuestion__r.Employee_test__c IN :testsIds
                                            AND Active__c = TRUE 
                                        GROUP BY TestQuestion__r.Employee_test__c];
        
        for (AggregateResult aggrResult : result) {
            Id testId = (Id)aggrResult.get('TestId');
            Integer OldNumberAnswers = Integer.valueOf(aggrResult.get('OldNumberAnswers'));
            Integer numAnswers = (Integer)aggrResult.get('NumberAnswers');

            if (OldNumberAnswers <> numAnswers) {             
                testsToUpdate.add(new EmployeeTest__c(Id = testId, NumberAnswers__c = numAnswers));
            }
        }

        if (!testsToUpdate.isEmpty()) {          
            update testsToUpdate;
        }
    }

    public static void changeEmployeeTestNumberAnswersWithMap(List<TestQuestionAnswer__c> questionAnswers) {
        List<EmployeeTest__c> testsToUpdate = new List<EmployeeTest__c>();

        Set<Id> testsIds = getTestIdsForQuestionAnswers(questionAnswers);
        
        Map<Id, Integer> testsIdsWithNumberAnswers = new Map<Id, Integer>();
        for (TestQuestionAnswer__c answer : [SELECT Id, TestQuestion__r.Employee_test__c
                                            FROM TestQuestionAnswer__c
                                            WHERE TestQuestion__r.Employee_test__c IN :testsIds 
                                                AND Active__c = TRUE]) {
            Id testId = answer.TestQuestion__r.Employee_test__c; 
            
            if (testsIdsWithNumberAnswers.containsKey(testId)) {
                testsIdsWithNumberAnswers.put(testId, testsIdsWithNumberAnswers.get(testId) + 1);        
            } else {
                testsIdsWithNumberAnswers.put(testId, 1);    
            }
        }

        for (Id key : testsIdsWithNumberAnswers.keySet()) {
            Integer numAnswers = testsIdsWithNumberAnswers.get(key);

            testsToUpdate.add(new EmployeeTest__c(Id = key, NumberAnswers__c = testsIdsWithNumberAnswers.get(key)));        
        }

        if (!testsToUpdate.isEmpty()) {          
            update testsToUpdate;
        }
    }

    private static Set<Id> getTestIdsForQuestionAnswers(List<TestQuestionAnswer__c> questionAnswers) {
        Set<Id> questionsIds = new Set<Id>();
        for (TestQuestionAnswer__c answer : questionAnswers) {
            questionsIds.add(answer.TestQuestion__c);
        }

        Set<Id> testsIds = new Set<Id>();
        for (TestQuestion__c question : [SELECT Id, Employee_Test__c
                                        FROM TestQuestion__c
                                        WHERE Id IN :questionsIds]) {
            testsIds.add(question.Employee_Test__c);                               
        }

        return testsIds;
    }
}