force-app/main/default/objects/EmployeeTest__c/EmployeeTest__c.object-meta.xml
<CustomObject>
    <label>Employee Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PassingTest__c/PassingTest__c.object-meta.xml
<CustomObject>
    <label>Passing Test</label>
    <nameField>
        <label>Passing Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passing Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PassingTest__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Passing Tests</relationshipLabel>
    <relationshipName>Passing_Tests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PassingTestTriggerHandlerTest.cls
@isTest
public with sharing class PassingTestTriggerHandlerTest {

    @TestSetup
    public static void setup() {
        Employee__c emp = TestDataFactory.getEmployeeBuilder()
            .buildEmployee();
        
        insert emp;

        EmployeeTest__c test = TestDataFactory.getEmployeeTestBuilder()
            .buildEmployeeTest();

        insert test;

        PassingTest__c passingTest = TestDataFactory.getPassingTestBuilder()
            .setEmployee(emp)
            .setEmployeeTest(test)
            .setStartDate(Datetime.now())
            .buildPassingTest();

        insert passingTest;    
    }

    @isTest
    public static void changeInvalidStartDateTest() {
        PassingTest__c passingTest = [SELECT Id FROM PassingTest__c WHERE Name = 'Test' LIMIT 1];
        passingTest.StartDate__c = Datetime.now();
        passingTest.EndDate__c = Datetime.now();

        Test.startTest();
        Database.SaveResult result = Database.update(passingTest, false);
        Test.stopTest();

        PassingTest__c updPassingTest = [SELECT Id, StartDate__c, EndDate__c FROM PassingTest__c WHERE Name = 'Test' LIMIT 1];

        Datetime expected = updPassingTest.EndDate__c - 60;
        Datetime actual = updPassingTest.StartDate__c;

        System.assertEquals(expected, actual, 'End date must be bigger than start date');
    }
}