force-app/main/default/objects/EmployeeTest__c/EmployeeTest__c.object-meta.xml
<CustomObject>
    <label>Employee Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmployeeTest__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TestQuestion__c/TestQuestion__c.object-meta.xml
<CustomObject>
    <label>Test Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestion__c/fields/Employee_Test__c.field-meta.xml
<CustomField>
    <fullName>Employee_Test__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Test</label>
    <referenceTo>EmployeeTest__c</referenceTo>
    <relationshipName>TestQuestions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestQuestion__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <summaryForeignKey>TestQuestionAnswer__c.TestQuestion__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TestQuestionAnswer__c/TestQuestionAnswer__c.object-meta.xml
<CustomObject>
    <label>Test Question Answer</label>
    <nameField>
        <label>Test Question Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestionAnswer__c/fields/TestQuestion__c.field-meta.xml
<CustomField>
    <fullName>TestQuestion__c</fullName>
    <label>Test Question</label>
    <referenceTo>TestQuestion__c</referenceTo>
    <relationshipLabel>Test Question Answers</relationshipLabel>
    <relationshipName>TestQuestionAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateTestNumberAnswersScheduledBatch.cls
public with sharing class UpdateTestNumberAnswersScheduledBatch implements Database.Batchable<sObject>, Schedulable {
    String Email;
    String query = 'SELECT Id FROM EmployeeTest__c WHERE Active__c = TRUE';
    
    public UpdateTestNumberAnswersScheduledBatch(String mail) {
    	Email = mail;    
    }
    
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new UpdateTestNumberAnswersScheduledBatch(Email));
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
      return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<EmployeeTest__c> scope) {
    	List<EmployeeTest__c> testsToUpdate = new List<EmployeeTest__c>();
        
        List<AggregateResult> result = [SELECT TestQuestion__r.Employee_test__c TestId, 
                                            MIN(TestQuestion__r.Employee_test__r.NumberAnswers__c) OldNumberAnswers, 
                                            COUNT(Id) NumberAnswers
                                        FROM TestQuestionAnswer__c
                                        WHERE TestQuestion__r.Employee_test__c IN :scope
                                            AND Active__c = TRUE 
                                        GROUP BY TestQuestion__r.Employee_test__c];
        
        for (AggregateResult aggrResult : result) {
            Id testId = (Id)aggrResult.get('TestId');
            Integer OldNumberAnswers = Integer.valueOf(aggrResult.get('OldNumberAnswers'));
            Integer numAnswers = (Integer)aggrResult.get('NumberAnswers');

            if (OldNumberAnswers != numAnswers) {             
                testsToUpdate.add(new EmployeeTest__c(Id = testId, NumberAnswers__c = numAnswers));
            }

            scope.remove(scope.indexOf(new EmployeeTest__c(Id = testId)));
        }

        for (EmployeeTest__c scope_i : scope) {
            scope_i.NumberAnswers__c = 0;
            testsToUpdate.add(scope_i);    
        }

        if (!testsToUpdate.isEmpty()) {          
            update testsToUpdate;
        }
    }
    
    public void finish(Database.BatchableContext bc) {
    	Messaging.SingleEmailMessage singleEmail = new Messaging.SingleEmailMessage();

        singleEmail.setToAddresses(new List<String> {Email});
        singleEmail.setSenderDisplayName('Batch Processing');
        singleEmail.setSubject('Batch Process for updating number answers of tests Completed');
        singleEmail.setPlainTextBody('Batch Process for updating number answers of tests has completed');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { singleEmail });    
    } 
}