force-app/main/default/objects/EmployeeTest__c/EmployeeTest__c.object-meta.xml
<CustomObject>
    <label>Employee Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmployeeTest__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TestQuestion__c/TestQuestion__c.object-meta.xml
<CustomObject>
    <label>Test Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestion__c/fields/Employee_Test__c.field-meta.xml
<CustomField>
    <fullName>Employee_Test__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Test</label>
    <referenceTo>EmployeeTest__c</referenceTo>
    <relationshipName>TestQuestions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestQuestion__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <summaryForeignKey>TestQuestionAnswer__c.TestQuestion__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TestQuestionAnswer__c/TestQuestionAnswer__c.object-meta.xml
<CustomObject>
    <label>Test Question Answer</label>
    <nameField>
        <label>Test Question Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestionAnswer__c/fields/TestQuestion__c.field-meta.xml
<CustomField>
    <fullName>TestQuestion__c</fullName>
    <label>Test Question</label>
    <referenceTo>TestQuestion__c</referenceTo>
    <relationshipLabel>Test Question Answers</relationshipLabel>
    <relationshipName>TestQuestionAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateTestNumberAnswersBatchTest.cls
@isTest
public with sharing class UpdateTestNumberAnswersBatchTest {
    public static String CRON_EXP = '0 54 19 * * ?';

    @TestSetup
    static void setup() {
        Integer numElements = 3;

        EmployeeTest__c employeeTest = TestDataFactory.createEmployeeTest();
        List<TestQuestion__c> questions = TestDataFactory.createTestQuestions(employeeTest, numElements);
        List<TestQuestionAnswer__c> answers = TestDataFactory.createTestQuestionAnswers(questions, numElements);
    } 
    
    @isTest
    static void executeTest() {
        Test.startTest();

        String mail = 'test@gmail.com';
        UpdateTestNumberAnswersScheduledBatch updBatch = new UpdateTestNumberAnswersScheduledBatch(mail);
        Id batchId = Database.executeBatch(updBatch);

        Test.stopTest();

        EmployeeTest__c empTest = [SELECT Id, NumberAnswers__c FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];

        Integer expected = 9;
        Integer actual = Integer.valueOf(empTest.NumberAnswers__c);

        System.assertEquals(expected, actual, 'Number of answers must be equals ' + expected);
    }

    @isTest
    static void executeWithDeletionRecordsTest() {
        List<TestQuestionAnswer__c> answers = [SELECT Id FROM TestQuestionAnswer__c WHERE TestQuestion__r.Employee_test__r.Name = 'Test'];
        delete answers;

        Test.startTest();
        String mail = 'test@gmail.com';
        UpdateTestNumberAnswersScheduledBatch updBatch = new UpdateTestNumberAnswersScheduledBatch(mail);
        Id batchId = Database.executeBatch(updBatch);

        Test.stopTest();

        EmployeeTest__c empTest = [SELECT Id, NumberAnswers__c FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];

        Integer expected = 0;
        Integer actual = Integer.valueOf(empTest.NumberAnswers__c);

        System.assertEquals(expected, actual, 'Number of answers must be equals ' + expected);
    }

    @isTest
    static void executeWithCronExpTest() {
        List<EmployeeTest__c> tests = [SELECT Id FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];
        List<Id> testsIds = new List<Id>(new Map<Id, EmployeeTest__c>(tests).keySet());

        Test.startTest();

        String mail = 'test@gmail.com';
        UpdateTestNumberAnswersScheduledBatch updBatch = new UpdateTestNumberAnswersScheduledBatch(mail);
        String jobId = System.schedule('UpdateTestNumberAnswers', CRON_EXP, updBatch);

        Test.stopTest();

        List<Task> lt = [SELECT Id FROM Task WHERE WhatId IN : testsIds];

        Integer expected = testsIds.size();
        Integer actual = lt.size();

        System.assertEquals(expected, actual, 'Tasks were not created');
    }
}