force-app/main/default/objects/EmployeeTest__c/EmployeeTest__c.object-meta.xml
<CustomObject>
    <label>Employee Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmployeeTest__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TestQuestion__c/TestQuestion__c.object-meta.xml
<CustomObject>
    <label>Test Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestion__c/fields/NumberAnswers__c.field-meta.xml
<CustomField>
    <fullName>NumberAnswers__c</fullName>
    <label>Number Answers</label>
    <summaryForeignKey>TestQuestionAnswer__c.TestQuestion__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TestQuestionAnswer__c/TestQuestionAnswer__c.object-meta.xml
<CustomObject>
    <label>Test Question Answer</label>
    <nameField>
        <label>Test Question Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TestQuestionAnswer__c/fields/TestQuestion__c.field-meta.xml
<CustomField>
    <fullName>TestQuestion__c</fullName>
    <label>Test Question</label>
    <referenceTo>TestQuestion__c</referenceTo>
    <relationshipLabel>Test Question Answers</relationshipLabel>
    <relationshipName>TestQuestionAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestQuestionAnswerTriggerHandlerTest.cls
@isTest
public with sharing class TestQuestionAnswerTriggerHandlerTest {
    @TestSetup
    static void setup(){
        EmployeeTest__c employeeTest = TestDataFactory.getEmployeeTestBuilder()
            .buildEmployeeTest();

        insert employeeTest;
    }

    @isTest
    static void changeEmployeeTestNumberAnswersTest() {
        Integer numElements = 3;

        EmployeeTest__c empTest = [SELECT Id FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];

        Test.startTest();

        List<TestQuestion__c> questions = new List<TestQuestion__c>();
        for (Integer i = 0; i < numElements; i++) {
            TestQuestion__c question = TestDataFactory.getTestQuestionBuilder()
                .setName('Question ' + i)
                .setEmployeeTest(empTest)
                .buildTestQuestion();

            questions.add(question);
        }
        insert questions;

        List<TestQuestionAnswer__c> answers = new List<TestQuestionAnswer__c>();      
        for (TestQuestion__c question : questions) {
            for (Integer i = 0; i < numElements; i++) {
                TestQuestionAnswer__c answer = TestDataFactory.getTestQuestionAnswerBuilder()
                    .setName('Answer ' + i)
                    .setTestQuestion(question)
                    .buildTestQuestionAnswer();
    
                answers.add(answer);
            }    
        }      
        insert answers;

        Test.stopTest();

        empTest = [SELECT Id, NumberAnswers__c FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];

        Integer expected = numElements * numElements;
        Integer actual = Integer.valueOf(empTest.NumberAnswers__c);

        System.assertEquals(expected, actual, 'Number of answers must be equals ' + expected);
    }

    @isTest
    static void changeUpdatedEmployeeTestNumberAnswersTest() {
        Integer numElements = 3;

        EmployeeTest__c empTest = [SELECT Id FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];

        Test.startTest();

        List<TestQuestion__c> questions = new List<TestQuestion__c>();
        for (Integer i = 0; i < numElements; i++) {
            TestQuestion__c question = TestDataFactory.getTestQuestionBuilder()
                .setName('Question ' + i)
                .setEmployeeTest(empTest)
                .buildTestQuestion();

            questions.add(question);
        }
        insert questions;

        List<TestQuestionAnswer__c> answers = new List<TestQuestionAnswer__c>();      
        for (TestQuestion__c question : questions) {
            for (Integer i = 0; i < numElements; i++) {
                TestQuestionAnswer__c answer = TestDataFactory.getTestQuestionAnswerBuilder()
                    .setName('Answer ' + i)
                    .setTestQuestion(question)
                    .buildTestQuestionAnswer();
    
                answers.add(answer);
            }    
        }      
        insert answers;

        answers[0].Active__c = false;
        update answers;

        empTest = [SELECT Id, NumberAnswers__c FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];

        Integer expected = numElements * numElements - 1;
        Integer actual = Integer.valueOf(empTest.NumberAnswers__c);

        System.assertEquals(expected, actual, 'Number of answers must be equal to amount of all test question answers related to employee test');

        delete answers;
        
        Test.stopTest();

        empTest = [SELECT Id, NumberAnswers__c FROM EmployeeTest__c WHERE Name = 'Test' LIMIT 1];

        expected = 0;
        actual = Integer.valueOf(empTest.NumberAnswers__c);

        System.assertEquals(expected, actual, 'Number of answers must be equal to amount of all test question answers related to employee test');
    }
}